project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Xiaohao Ji"
  site-url: https://github.com/ji-xiaohao
  favicon: images/site-logo.png
  repo-url: https://github.com/ji-xiaohao/ji-xiaohao.github.io
  repo-actions: [edit, issue]
  
  page-footer:
    left: |
      [lianxh.cn](https://www.lianxh.cn)<br>
    right: |
      Made with [Quarto](https://quarto.org/)<br>
    
  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: " Machine Learning"
        href:  Machine Learning.qmd
      - text: "Deep Learning"
        href: Deep Learning.qmd
      - text: "Power BI"
        href: Power BI.qmd
      - text: "Paper Reading"
        href: Paper Reading.qmd
      - text: "中文"
        href: Chinese.qmd

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细