---
title: "Machine Learning"
editor: 
  markdown: 
    wrap: 72
---

本板块展示了我在以下方向的部分实践成果：

·Python 数据分析

聚焦上市公司财务数据，运用 Python 进行数据清洗、指标构建与可视化分析，深入挖掘企业在财务健康状况、资本结构特征及经营风险等方面的动态表现，助力财务洞察与决策支持。

·机器学习应用研究

基于 A 股市场公司数据，结合 XGBoost、GBDT、Lasso 等机器学习模型，探索企业成本费用、股权结构特征、审计意见判断及估值差异等实际问题，重点关注模型在真实场景中的可解释性。



&emsp;

## 1.python分析
### python——普利制药财务舞弊分析
本项目基于叶钦华等（2022）发表于《会计研究》的《财务舞弊识别框架构建——基于会计信息系统论及大数据视角》，使用 Python 对普利制药的财务数据进行系统性分析。通过构建盈利能力、现金流异常、关联交易等关键指标，尝试从数据中捕捉潜在的风险信号，评估其财务健康状况。

📄相关分析报告详见：[python——普利制药财务舞弊分析.pdf](python——普利制药财务舞弊分析.pdf)


### python——小米数据分析
本项目运用 Python 对小米集团的财务报表数据进行全面分析，并通过可视化手段动态呈现其关键财务指标的演变趋势与当前状态。研究聚焦于资本结构、融资策略及财务风险水平等方面。

📄相关分析报告详见：[python——小米数据分析.pdf](python——小米数据分析.pdf)

## 1.机器学习项目
### 机器学习——成本管理模型
基于沪深京市场A股上市公司2018年至2024年的年度财务数据，本文尝试对企业的成本与费用结构进行建模分析。

模型部分使用 scikit-learn 中的线性回归和梯度提升决策树（GBDT）进行对比实验，旨在比较线性回归与非线性方法在拟合企业成本行为上的表现差异，初步评估不同模型在解释费用结构变化中的适用性。
📄相关报告详见：[机器学习——成本管理模型.pdf](机器学习——成本管理模型.pdf)


### 机器学习——股权特征与企业市场价值
本项目旨在通过机器学习方法深入探究关注 A 股上市公司的股权特征的典型事实及其对企业市场价值的影响。通过可视化手段直观展示两权分离度、机构持股信息等关键指标的分布情况。进一步地，对制造业与非制造业、国企与非国企进行分组对比分析，以揭示不同行业和所有制类型在股权结构上的差异及其对企业市场价值的潜在影响。

在模型训练与评估阶段，项目采用了梯度提升树（GBDT）模型和Lasso回归两种算法，能够更准确地量化股权特征与企业市场价值之间的关系。

📄相关报告详见：[机器学习——股权特征与企业市场价值.pdf](机器学习——股权特征与企业市场价值.pdf)

### 机器学习——关键审计事项多标签分类
本项目旨在探索不同类别关键审计事项下，企业基本面特征对审计判断的差异化影响。具体聚焦于五类高频关键审计事项：收入确认（Revenue）、其他事项（Other）、应收账款（Accounts Receivable）、无形资产（Intangible Assets）和存货（Inventories）。

基于上市公司公开披露的审计报告与财务数据，构建了分类标签，并选取一系列公司层面的解释变量，包括规模（SIZE）、上市年限（AGE）、账面市值比（BM）、销售增长率（SALES-GROWTH）、杠杆率（LEV）、盈利能力（ROA）、亏损状态（LOSS）等。

在此基础上，采用 XGBoost 模型对每一类关键审计事项分别建模，利用其特征重要性（Feature Importance）和SHAP值分析，识别在不同审计事项下哪些变量具有更强的预测能力，进而比较“什么因素让审计师更关注收入？什么因素更易触发无形资产减值审计？”等问题上的差异。

📄相关报告详见：[机器学习——关键审计事项多标签分类.pdf](机器学习——关键审计事项多标签分类.pdf)

### 机器学习——国有、民营的估值差异
本项目使用 XGBoost 机器学习模型，探讨国企与民营企业在估值上的差异及其影响因素。以市净率（PB）作为估值指标，考察企业性质（EquityNature）、资本支出（Capexp）、第一大股东持股比例（LargestHolderRate）、前十股东持股比例（TopTenHoldersRate），以及公司规模（size）、固定资产占比（ppe_ratio）、无形资产占比（intangible_ratio）、资产负债率（lev）、毛利率（Gross_Margin）和公司年龄（age）等因素对估值的影响，旨在识别国企与民营企业在市场定价中的表现差异。


📄相关报告详见：[机器学习——国有、民营的估值差异.pdf](机器学习——国有、民营的估值差异.pdf)